### PR TITLE
fix: syntax error when arrow function parameter is assignment pattern

### LINKED ISSUE #7: Syntax error when arrow function parameter is assignment pattern
The following code seems to give a syntax error when using acorn-typescript.

```ts
a = (x = 42) => {}
```

The following code is to reproduce.

```ts
import * as acorn from "acorn";
import { tsPlugin } from "acorn-typescript";

const acornTs = acorn.Parser.extend(tsPlugin());

const code = "a = (x = 42) => {}";

const options = {
  sourceType: "module",
  ecmaVersion: "latest",
  locations: true,
} as const;

// OK
let node = acorn.Parser.parse(code, options);
console.log(node);

// Error
node = acornTs.parse(code, options);
console.log(node);
```

Use Versions:

```
    "acorn": "^8.8.2",
    "acorn-typescript": "^1.2.7",
```

### PR DESCRIPTION
**Pull request by ota-meshi**
fixes #7

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -4446,7 +4446,6 @@ function tsPlugin(options?: {
             if (!isBinding && node.left.type === 'TSTypeCastExpression') {
               node.left = this.typeCastToParameter(node.left)
             }
-            return node
```
Comment (TyrealHu) [inline src/index.ts:4449]: Could u use return super.toAssignable instead of delete the return syntax?

Comment (ota-meshi) [reply src/index.ts:4449]: Thank you for checking this PR!
I changed that.
